Repository mercadolibre/mobile-dependencies_whitelist, pull requests merged in 2022-12, with the labels that each got.

#1599 WebP animated - Fresco module.json
  android-whitelist.json
Labels: CaseReview

#1606 bump expire date firebase ads
  android-whitelist.json
Labels: DONE

#1598 Added SPGlobeWrapper
  ios-whitelist.json
Labels: CaseReview

#1615 Update android-whitelist.json
  android-whitelist.json
Labels: DONE

#1616 upgrade devices-sdk 5.0.0
  android-whitelist.json
Labels: DONE

#1614 Feature/bump biometric UI
  ios-whitelist.json
Labels: DONE

#1610 [MPoC PoC] Whitelist lib testing
  android-whitelist.json
Labels: DONE

#1603 add Flipper library to use in developer mode
  android-whitelist.json
Labels: DONE

#1609 - Bump Dami Ui lib to 2.0.0
  android-whitelist.json
Labels: DONE

#1621 Modify import for authentication
  android-whitelist.json
Labels: DONE

#1626 Daisy-whitelist
  android-whitelist.json
Labels: ChangesRequested

#1629 Add new repo in white list
  android-whitelist.json
Labels: DONE

#1628 Bump MelidataSDK to 16.+
  android-whitelist.json
Labels: DONE

#1630 New MPlay Lib
  android-whitelist.json
Labels: DONE

#1631 Shorts webview libraries are added to the whitelist files
  android-whitelist.json
  ios-whitelist.json
Labels: DONE

#1632 [Feature] updated globe lib from 2.2.1-52 to 2.2.5-55
  android-whitelist.json
Labels: DONE

#1638 add new module configurer OnDemandResources
  android-whitelist.json
Labels: DONE

#1637 bump qadb version
  android-whitelist.json
Labels: DONE

#1640 Add: dependence hub-engine
  android-whitelist.json
Labels: DONE
