Repository mercadolibre/mobile-dependencies_whitelist, pull requests merged in 2022-10, with the labels that each got.

#1525 Search update expires date
  android-whitelist.json
Labels: DONE

#1524 Added expires date in mlwebkit version 2
  android-whitelist.json
Labels: DONE

#1522 Update expires Insurance Qpage and FloxComponent
  android-whitelist.json
Labels: DONE

#1529 Update android-whitelist.json
  android-whitelist.json
Labels: DONE

#1533 [Reviews] Bump version
  android-whitelist.json
Labels: DONE

#1528 [QADB] Bump version to 6
  android-whitelist.json
Labels: DONE

#1535 livecommerce 3
  android-whitelist.json
Labels: DONE

#1545 Loyalty changes
  android-whitelist.json
Labels: CaseReview

#1530 [MODS] Updated major for BSUI
  ios-whitelist.json
Labels: ChangesRequested
