Repository mercadolibre/mobile-dependencies_whitelist, pull requests merged in 2023-09, with the labels that each got.

#2036 [Update] change the expiration date MPContacts
  ios-whitelist.json
Labels: DONE

#2035 Add lib wishlists Android
  android-whitelist.json
Labels: DONE

#2032 Adding SmartTokenization v2
  ios-whitelist.json
Labels: DONE

#2038 MLThreeDS Version 2.0.6
  ios-whitelist.json
Labels: CaseReview

#1949 Bump Restclient and OkHttp
  android-whitelist.json
Labels: WIP

#2043 [Feature] Rollback Globe lib from 2.2.5-55 to 2.2.1-52
  android-whitelist.json
Labels: DONE

#2048 [Feature] Upgrade version to reviews lib and shorts lib.
  android-whitelist.json
Labels: DONE

#2052 Bump Login 18.0.0
  android-whitelist.json
Labels: DONE

#2053 Expire ml-cards
  android-whitelist.json
Labels: DONE

#2054 upgrade lib version
  android-whitelist.json
Labels: DONE

#2057 Update android-whitelist.json
  android-whitelist.json
Labels: DONE

#2074 Update buyingflow payment version
  ios-whitelist.json
Labels: DONE

#2068 Bump AppMonitoring version 2
  android-whitelist.json
Labels: DONE

#2067 Bumps major Rael Estates Everywhere repositories
  android-whitelist.json
Labels: DONE

#2076 Bumping Onboarding and Pendings - Kotlin 1.8
  android-whitelist.json
Labels: DONE

#2078 [Insurance] QPageOn
  android-whitelist.json
Labels: DONE

#2077 Error handler v2 added and v1 marked as deprecated
  android-whitelist.json
Labels: DONE

#2084 [Feature] Upgrade version to qadb lib.
  android-whitelist.json
Labels: DONE
