Repository mercadolibre/mobile-dependencies_whitelist, pull requests merged in 2023-10, with the labels that each got.

#2083 update fees version
  android-whitelist.json
Labels: DONE

#2082 Update version due to kotlin migration
  android-whitelist.json
Labels: DONE

#2086 Bump DAMI UI to v4
  android-whitelist.json
Labels: DONE

#2093 Update android-whitelist.json
  android-whitelist.json
Labels: DONE

#2097 Bumping usersections due to kotlin migration
  android-whitelist.json
Labels: DONE

#2099 Bumping merchengine - Kotlin 1.8
  android-whitelist.json
Labels: DONE

#2096 bump seller-home-sections dashboards tfs-commons collaboratorsui kotlin 1.8 migration
  android-whitelist.json
Labels: DONE

#2101 Bump Credits Behaviour 6.0.0
  android-whitelist.json
Labels: DONE

#2100 Nuevas versiones de libs de checkout
  android-whitelist.json
Labels: DONE

#2104 Remove credits behaviour 6.0.0
  android-whitelist.json
Labels: DONE

#2112 [mPOC] Add sdk contactless dependency to whitelist
  android-whitelist.json
Labels: DONE

#2111 [mPOC] Update dependency library group id.
  android-whitelist.json
Labels: DONE

#2109 [Feat]: bump smart tokenization v3, congrats-sdk v2 and esc manager v7
  android-whitelist.json
Labels: DONE

#2107 Home added
  android-whitelist.json
Labels: DONE

#2105 MLHome added
  ios-whitelist.json
Labels: DONE

#2108 bump libs credit-toolkit
  android-whitelist.json
Labels: DONE

#2110 Add app-monitoring-ios 2.0
  ios-whitelist.json
Labels: CaseReview

#2085 Card Form V5.0.0
  android-whitelist.json
Labels: DONE

#2130 Floxclient core new version 4
  android-whitelist.json
Labels: DONE

#2132 update cardForm to v6
  ios-whitelist.json
Labels: DONE

#2133 Expiration time extended for ML-scanner lib version
  android-whitelist.json
Labels: CaseReview

#2146 [Feat]: bump SecureInputs v2
  android-whitelist.json
Labels: ChangesRequested

#2149 Add mobile permissions
  android-whitelist.json
Labels: DONE
