Repository mercadolibre/mobile-dependencies_whitelist, pull requests merged in 2023-12, with the labels that each got.

#2199 cardForm - Updating v5 cardForm expires date
  android-whitelist.json
  ios-whitelist.json
Labels: DONE

#2202 Add AmountScreen lib
  android-whitelist.json
  ios-whitelist.json
Labels: DONE

#2190 Unbundled MLKit Barcode dependencie bumped
  android-whitelist.json
Labels: CaseReview

#2213 Include version 7 of POS-SDK.
  android-whitelist.json
Labels: DONE

#2211 Bump CashRails
  android-whitelist.json
Labels: DONE

#2212 Update Selling Framework libraries
  android-whitelist.json
Labels: CaseReview

#2220 Navigation Router support for 2.x versions
  ios-whitelist.json
Labels: CaseReview

#2208 Bump Datadog
  android-whitelist.json
Labels: DONE

#2080 Bumped ml qualtrics libs due to kotlin migration
  android-whitelist.json
Labels: DONE

#2226 Update Checkout marketplace-map version
  android-whitelist.json
Labels: DONE

#2225 addresses version 8 was deprecated and 9 is enabled now.
  android-whitelist.json
Labels: DONE

#2235 Firebase perf expires date extend
  android-whitelist.json
Labels: DONE

#2223 Update MLCharts
  ios-whitelist.json
Labels: DONE

#2231 [CHANGED] Portable Widget
  android-whitelist.json
Labels: DONE

#2233 [Update] Android Navigation Components expiration dates
  android-whitelist.json
Labels: DONE

#2232 [SMART-5161] - Adding new libraries for smartPOS
  android-whitelist.json
Labels: ChangesRequested

#2230 Update navigation libs version
  android-whitelist.json
Labels: DONE

#2240 Update Datadog libs
  android-whitelist.json
Labels: DONE

#2238 Update SplitPayment and Payments
  ios-whitelist.json
Labels: DONE

#2194 Added androidx tracing for measure times
  android-whitelist.json
Labels: DONE

#2239 [SMART-5165] Include version 1.0.0 in remote config
  android-whitelist.json
Labels: DONE

#2243 Updated the allowed version of Webkit.
  android-whitelist.json
Labels: DONE

#2247 Add Comparator 9.+
  android-whitelist.json
Labels: DONE

#2246 bump search libs
  android-whitelist.json
Labels: DONE

#2254 [SMARTI-1102] Add smartHelpers version.
  android-whitelist.json
Labels: CaseReview
