Repository mercadolibre/mobile-dependencies_whitelist, pull requests merged in 2023-06, with the labels that each got.

#1879 Add autosuggest ios module
  ios-whitelist.json
Labels: DONE

#1878 Add more like this ios module
  ios-whitelist.json
Labels: DONE

#1867 bump recos lib to 3.+
  android-whitelist.json
Labels: CaseReview

#1895 [PSF-211] Add Selling Framework libraries
  android-whitelist.json
Labels: DONE

#1894 Update Gson and Grpc versions
  android-whitelist.json
Labels: ChangesRequested

#1912 added +jason for new library implementation
  android-whitelist.json
Labels: CaseReview

#1923 [iOS] bump SecureInputs lib
  ios-whitelist.json
Labels: DONE

#1921 Add AutoSuggest android
  android-whitelist.json
Labels: DONE

#1926 Deprecate instore geofencing
  android-whitelist.json
Labels: DONE

#1924 Feature/security preferences v8
  android-whitelist.json
Labels: DONE

#1929 Nueva version de native reauth
  android-whitelist.json
Labels: DONE

#1928 Add MQTT version 1.0.0
  android-whitelist.json
Labels: DONE

#1933 Edit totpinapp version and expired date
  android-whitelist.json
Labels: DONE
