Repository mercadolibre/mobile-dependencies_whitelist, pull requests merged in 2023-08, with the labels that each got.

#1984 Se actualiza el major de riskmanagement
  android-whitelist.json
Labels: DONE

#1801 Bump datadog version
  android-whitelist.json
Labels: DONE

#1990 [ISPMPOS-744] Updated MPP version and created whitelist to mPOC libraries
  android-whitelist.json
Labels: DONE

#1987 feat: add ccap-commons's dependence
  android-whitelist.json
Labels: DONE

#1980 MyAccountClient Dependency
  ios-whitelist.json
Labels: DONE

#1994 Bump app_monitoring
  android-whitelist.json
Labels: DONE

#1997 Checkout y checkout sdk, nuevas versiones
  android-whitelist.json
Labels: DONE

#1999 [Search] Bump version to 18
  android-whitelist.json
Labels: DONE

#2004 Add CcapCommons
  ios-whitelist.json
Labels: DONE

#2005 [Update] change the expiration date for MPContacts
  ios-whitelist.json
Labels: DONE

#2007 Dependencies cart upgrade - Version kotlin
  android-whitelist.json
Labels: DONE

#2002 Update Braze SDK to -> 26.1.1.
  android-whitelist.json
Labels: WIP

#2006 update version interactivemedia Ads library
  android-whitelist.json
Labels: DONE

#1975 Se agrega sdk BrazeKitCompat y se agrega fecha de vencimiento a SDK A…
  ios-whitelist.json
Labels: CaseReview

#2011 Added Mobile Permissions library
  ios-whitelist.json
Labels: DONE

#2008 [ISPFSF] Added selling data library
  android-whitelist.json
Labels: DONE

#2018 Bump Core Flox
  android-whitelist.json
Labels: DONE

#2020 Bump Payment
  android-whitelist.json
Labels: DONE

#2022 Se agrega la Nueva librería Scoped Session Android
  android-whitelist.json
Labels: DONE

#2024 [Feat]: ESC Manager bump to 6.+ and expires 5.+
  android-whitelist.json
Labels: CaseReview
