Repository mercadolibre/mobile-dependencies_whitelist, pull requests merged in 2024-07, with the labels that each got.

#2687 ml-scanner-android version added
  android-whitelist.json
Labels: DONE

#2689 Adding new lib iOS: TransfersComponents
  ios-whitelist.json
Labels: DONE

#2690 Update commons version to 38
  android-whitelist.json
Labels: DONE

#2692 Extend the expiration date of Firebase Performance
  android-whitelist.json
Labels: DONE

#2698 Add advertising analytics dependency
  android-whitelist.json
Labels: DONE

#2697 [Add] Transfer Components Core v0.1.0
  android-whitelist.json
Labels: DONE

#2702 Native Reauth 8 and Reauth Adapter 5
  android-whitelist.json
Labels: DONE

#2667 Bump Flox 13 with Android 14 support
  android-whitelist.json
Labels: DONE

#2707 Update cross-kmp-allowlist.json
  cross-kmp-allowlist.json
Labels: DONE

#2710 Update globe version
  android-whitelist.json
Labels: DONE

#2708 Review V6 dependency added to whitelist
  android-whitelist.json
  ios-whitelist.json
Labels: DONE

#2709 MLMap version updated
  ios-whitelist.json
Labels: DONE

#2701 Fix nav manager 7.+
  android-whitelist.json
Labels: ChangesRequested

#2713 update reviews whitelist
  android-whitelist.json
Labels: DONE

#2685 Add VerticalsCore to whitelist
  android-whitelist.json
  ios-whitelist.json
Labels: DONE

#2704 [CCAP-6890] Smart tokenization v5
  android-whitelist.json
Labels: DONE, Android

#2711 [ISPMPOS-2646]Bump mpos libs
  android-whitelist.json
Labels: DONE, Android

#2714 Update request watcher lib
  android-whitelist.json
Labels: DONE, Android

#2716 Bump up Screenlock libs - Android 14
  android-whitelist.json
Labels: DONE, Android

#2718 [Feature] Bump usdk version
  android-whitelist.json
Labels: DONE

#2696 [bump] Update Error Handler v4
  android-whitelist.json
Labels: CaseReview, Android

#2724 Add multiplayer to granular projects of transfers_components dependency
  android-whitelist.json
Labels: DONE

#2583 Bump interactivemedia to 3.34.0
  android-whitelist.json
Labels: DONE

#2728 Update Traceability 11.+
  android-whitelist.json
Labels: DONE

#2732 DHV-4300-Add DemandCore to whitelist
  ios-whitelist.json
Labels: DONE

#2729 Scanners 14 version expire date changed
  android-whitelist.json
Labels: DONE

#2743 [Android] Update Instore UI
  android-whitelist.json
Labels: DONE

#2744 [Added] - Add AdvertisingAnalytics to ios-whitelist.json
  ios-whitelist.json
Labels: DONE

#2748 Added HorizontalCards in ios-whitelist.json
  ios-whitelist.json
Labels: DONE

#2736 update lib wishlists Android 5.0
  android-whitelist.json
Labels: DONE

#2734 Update BitmovinPlayer ios-whitelist.json
  ios-whitelist.json
Labels: CaseReview

#2747 Update sdk braze to -> 31.
  android-whitelist.json
Labels: CaseReview

#2752 Allow Firebase&GPS new versions and added project in granularity
  android-whitelist.json
Labels: DONE
