Repository mercadolibre/mobile-dependencies_whitelist, pull requests merged in 2024-04, with the labels that each got.

#2419 Add Screenshots iOS lib to allowlist
  ios-whitelist.json
Labels: DONE

#2420 Add new lib Android meli screenshots
  android-whitelist.json
Labels: DONE

#2435 Firebase perf expires date
  android-whitelist.json
Labels: DONE

#2357 Added rules for SwiftUI subspecs
  ios-whitelist.json
Labels: WIP

#2429 Update commons
  android-whitelist.json
Labels: CaseReview

#2432 Add PxTokenization
  ios-whitelist.json
Labels: CaseReview

#2440 Add business_component
  android-whitelist.json
Labels: DONE

#2444 bump secure-inputs
  android-whitelist.json
Labels: DONE

#2397 Traceability version 9.0.0
  android-whitelist.json
Labels: DONE

#2438 Update RestClient 25
  android-whitelist.json
Labels: DONE

#2442 Add granular dependency to developer mode. modify date expires.
  android-whitelist.json
Labels: DONE

#2443 new version at expires webkit
  android-whitelist.json
Labels: DONE

#2425 Add MAI dependencies with granularity
  android-whitelist.json
Labels: WIP

#2423 bumped qualtrics sdk
  android-whitelist.json
Labels: DONE

#2448 add allowlist to bottomsheet module of demand core
  android-whitelist.json
Labels: DONE

#2452 Bump version RemoteConfigurations
  android-whitelist.json
Labels: DONE

#2453 Update Restclient
  android-whitelist.json
Labels: DONE

#2474 Extend restclient-adapter-rx2:24 for intent-fix purpose
  android-whitelist.json
Labels: DONE

#2459 Add FeedbackScreen to be an early Andes/SwiftUI adopter
  ios-whitelist.json
Labels: DONE

#2468 Bump NavigationCP v12, UINavigationCP v10 and XprodModules v2.
  android-whitelist.json
Labels: DONE

#2477 Update reglas Firebase
  ios-whitelist.json
Labels: DONE

#2483 Update SL libs
  android-whitelist.json
Labels: DONE

#2484 Notification helpers v6
  android-whitelist.json
Labels: DONE

#2486 [iOS][AdvertisingADN] - Expired date updated.
  ios-whitelist.json
Labels: DONE

#2491 [PX] Remove duplicated libs
  ios-whitelist.json
Labels: DONE

#2422 Bump Search to 20.+
  android-whitelist.json
Labels: DONE

#2485 Change Screenshots name to MLScreenshots
  ios-whitelist.json
Labels: DONE

#2488 [ANDROID] New Version ADN V8
  android-whitelist.json
Labels: DONE

#2471 Update libs bajo ownership del equipo Proximity
  android-whitelist.json
Labels: DONE

#2500 Add reauth native version 7
  android-whitelist.json
Labels: DONE

#2505 Update Viewability version
  android-whitelist.json
Labels: DONE

#2503 Feature/bump melidata 20
  android-whitelist.json
Labels: DONE

#2497 Update ios-whitelist.json MLBiometricSecurity and BiometricSecurityUI
  ios-whitelist.json
Labels: DONE

#2493 Change expiration date of security_two_fa libraries
  android-whitelist.json
Labels: DONE

#2499 Bump Bugsnag Lib to 6.4 and Update Expires for 5.29
  android-whitelist.json
Labels: DONE
