Repository mercadolibre/mobile-dependencies_whitelist, pull requests merged in 2024-02, with the labels that each got.

#2304 Expiration date changed
  android-whitelist.json
Labels: DONE

#2309 add CcapSDUI
  android-whitelist.json
  ios-whitelist.json
Labels: DONE

#2317 bump libdataprivacy
  android-whitelist.json
Labels: DONE

#2315 Bump authentication y AuthenticationEnrollment v25.+
  android-whitelist.json
Labels: DONE

#2320 agregando nueva libraria cart-facade:proxy:1.1.0
  android-whitelist.json
Labels: DONE

#2323 add new lib wrapper qr generator
  android-whitelist.json
Labels: DONE

#2321 Update lib version.
  android-whitelist.json
Labels: DONE

#2308 [Feature] Add Virtual Try On dependencies
  android-whitelist.json
  ios-whitelist.json
Labels: CaseReview

#2319 Remove MLCollaboratorsV2
  ios-whitelist.json
Labels: DONE

#2327 bump recos
  android-whitelist.json
Labels: DONE

#2330 Allow Selling Framework version 3.+
  android-whitelist.json
Labels: DONE

#2340 Bump Restclient and Everest
  android-whitelist.json
Labels: DONE

#2339 Remove CardForm v6 from Android Whitelist
  android-whitelist.json
Labels: DONE

#2336 [iOS] Bump IspSf to 4.0.0
  ios-whitelist.json
Labels: DONE

#2325 Remove the expiration date from cardForm
  ios-whitelist.json
Labels: DONE

#2272 Update Bitmovin version
  android-whitelist.json
Labels: CaseReview

#2345 [SMART-5603] Add Reader Manager SF lib to the allow list
  android-whitelist.json
Labels: DONE

#2331 Revert FeedbackScreen changes on the whitelist
  ios-whitelist.json
Labels: WIP

#2334 [Feature] Add Virtual Try On in Android
  android-whitelist.json
Labels: WIP

#2363 [Update] DaComponents version 8.+ and added expiration date to version 7.+
  android-whitelist.json
Labels: DONE
